
include 'Main.asm'
include 'ThreadProcessMessages.asm'

include 'app/AppDrawConsoleLog.asm'
include 'app/AppInit.asm'
include 'app/AppUpdate.asm'
include 'app/AppDrawInputLine.asm'
include 'app/AppDrawLogo.asm'
include 'app/AppRecalculateWindowSize.asm'

include 'console/ConsoleInit.asm'
include 'console/ConsoleClear.asm'
include 'console/ConsoleAddCommand.asm'
include 'console/ConsoleFlushBuffers.asm'
include 'console/ConsolePrint.asm'
include 'console/ConsolePrintLine.asm'
include 'console/ConsoleInputHandle.asm'

include 'window/WindowSurfaceFlush.asm'
include 'window/WindowCreate.asm'
include 'window/WindowProc.asm'

include 'io/InputBufferAddChar.asm'
include 'io/InputBufferRemoveChar.asm'
include 'io/InputBufferClear.asm'
include 'io/InputOnKeyDown.asm'
include 'io/OutputBufferAddString.asm'
include 'io/OutputBufferClear.asm'

include 'draw/BufferCreate.asm'
include 'draw/BufferResize.asm'
include 'draw/DrawBuffer.asm'
include 'draw/DrawBufferScaled.asm'
include 'draw/DrawClear.asm'
include 'draw/DrawSetTarget.asm'
include 'draw/DrawPixel.asm'
include 'draw/DrawPixelChar.asm'
include 'draw/DrawPixelText.asm'
include 'draw/DrawPixelTextOutline.asm'
include 'draw/DrawLineHorizontal.asm'
include 'draw/DrawRectangle.asm'