include 'ArrayListClear.asm'
include 'ArrayListCreate.asm'
include 'ArrayListGet.asm'
include 'ArrayListGetLast.asm'
include 'ArrayListPop.asm'
include 'ArrayListPush.asm'
include 'ArrayListSize.asm'