include 'InputBufferAddChar.asm'
include 'InputBufferRemoveChar.asm'
include 'InputBufferClear.asm'
include 'InputOnChar.asm'
include 'OutputBufferAddString.asm'
include 'OutputBufferAddChar.asm'
include 'OutputBufferClear.asm'