include 'InputBufferAddChar.asm'
include 'InputBufferRemoveChar.asm'
include 'InputBufferClear.asm'
include 'InputOnKeyDown.asm'
include 'OutputBufferAddString.asm'
include 'OutputBufferAddChar.asm'
include 'OutputBufferClear.asm'