include 'ConsoleInit.asm'
include 'ConsoleClear.asm'
include 'ConsoleAddCommand.asm'
include 'ConsoleFlushBuffers.asm'
include 'ConsoleInputHandle.asm'
include 'ConsolePrint.asm'
include 'ConsolePrintLine.asm'
include 'ConsolePrintChar.asm'